CREATE TABLE USER (
	ROLL_NO VARCHAR(9) PRIMARY KEY,
	PASSWORD VARCHAR(50) NOT NULL ,
	FIRST_NAME VARCHAR(50) NOT NULL,
	MIDDLE_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	YEAR VARCHAR(2) NOT NULL, 
	DIVISION VARCHAR(1) NOT NULL,
	BATCH INT(1) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MOBILE_NUMBER VARCHAR(15) NOT NULL
);

--year as in fe,se,te,be
